runtime: nodejs14
env: standard
instance_class: F1

env_variables:
  DATABASE_URL: "mysql://servers:123456@34.50.84.32/sibolang"
  JWT_SECRET: "4f8a8a729e28d2bf6c2f3c3b5a3e5f5a2b4c2d6e3c8a8d5a2d5f6e2b4a6b5c2e"
  PORT: 3000
  HOST: "localhost"
