steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$dicodingcapstone/app', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$dicodingcapstone/app']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'YOUR_SERVICE_NAME', '--image', 'gcr.io/$dicodingcapstone/app', '--region', 'YOUR_REGION', '--platform', 'managed']

images:
- 'gcr.io/$dicodingcapstone/app'
